INSERT INTO GAME (game_id, status) values(1, 'O');
INSERT INTO GAME (game_id, status) values(2, 'O');
INSERT INTO GAME (game_id, status) values(3, 'O');
INSERT INTO GAME (game_id, status) values(4, 'O');
INSERT INTO GAME (game_id, status) values(5, 'O');
INSERT INTO GAME (game_id, status) values(6, 'O');
INSERT INTO GAME (game_id, status) values(7, 'O');
INSERT INTO GAME (game_id, status) values(8, 'O');
INSERT INTO GAME (game_id, status) values(9, 'O');

INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(1, 3, 0, 105);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(1, 2, 1, 12);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(1, 1, 2, 14);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(1, 4, 3, 55);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(2, 3, 0, 80);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(2, 2, 1, 16);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(2, 1, 2, 102);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(2, 4, 3, 10);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(3, 3, 0, 101);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(3, 2, 1, 6);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(3, 1, 2, 4);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(3, 4, 3, 5);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(4, 3, 0, 34);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(4, 2, 1, 106);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(4, 1, 2, 4);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(4, 4, 3, 55);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(5, 3, 0, 103);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(5, 2, 1, 6);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(5, 1, 2, 40);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(5, 4, 3, 57);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(6, 6, 0, 90);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(6, 2, 1, 12);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(6, 3, 2, 104);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(6, 4, 3, 55);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(7, 6, 0, 80);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(7, 2, 1, 16);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(7, 3, 2, 104);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(7, 4, 3, 10);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(8, 6, 0, 10);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(8, 2, 1, 106);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(8, 3, 2, 4);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(8, 4, 3, 5);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(9, 6, 0, 34);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(9, 2, 1, 106);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(9, 3, 2, 4);
INSERT INTO GAME_PLAYER (game_id, player_id, position, score) values(9, 4, 3, 55);